@startuml Sprint Calendar for 22.1 PI

class "Sprint 1" {
  Time: January 3 - January 14
  'void methods()
}

class "Sprint 2" {
  Time: January 17 - January 28
  'void methods()
}

class "Sprint 3" {
  Time: January 31 - February 11
  'void methods()
}

class "Sprint 4" {
  Time: February 14 - February 25
  'void methods()
}

class "Sprint 5" {
  Time: February 28 - March 11
  'void methods()
}

class "Sprint 6" {
  Time: March 14 - March 25
  'void methods()
}

class "PI Planning" {
  Time: March 28 - April 1
  'void methods()
}

@enduml