openapi: 3.0.1
info:
  title: Swagger Medical Record Microservice
  description: 'Microservice Hospital Patient Data Project'
  contact:
    email: jaredr.branscum@gmail.com
  version: 0.0.1
servers:
- url: http://localhost:8080/v1
paths:
  /user:
    $ref: "paths/user.yaml"
