@startuml Sprint Calendar for 22.2 PI

class "Sprint 1" {
  Time: April 4 - April 15
  'void methods()
}

class "Sprint 2" {
  Time: April 18 - April 29
  'void methods()
}

class "Sprint 3" {
  Time: May 2 - May 13
  'void methods()
}

class "Sprint 4" {
  Time: May 16 - May 27
  'void methods()
}

class "Sprint 5" {
  Time: May 30 - June 10
  'void methods()
}

class "Sprint 6" {
  Time: June 13 - June 24
  'void methods()
}

class "PI Planning" {
  Time: June 27 - July 1
  'void methods()
}

@enduml