openapi: 3.0.1
info:
  title: Swagger Medical Record Microservice
  description: 'Microservice Hospital Patient Data Project'
  license:
    name: MIT
  contact:
    name: Jared Branscum
    email: jaredr.branscum@gmail.com
  version: 0.0.1
servers:
- url: http://localhost:8080/v1
paths:
    $ref: "./resources/user/user.yaml"

components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"